In [ ]:
faqs = """Why LSTM Exists (Problem First)

Classic RNNs fail at long-term dependencies because of:

Vanishing gradients

Exploding gradients

👉 They forget information that’s far back in time.

LSTM (Long Short-Term Memory) fixes this by controlling what to remember, forget, and output.

2️⃣ Core Idea (One Line)

LSTM uses gates + a memory cell to selectively store long-term information.

Think of it as:

Memory cell = long-term storage

Gates = smart controllers

3️⃣ LSTM Architecture (Inside the Cell)

At time step t, LSTM has:

Input: xₜ

Hidden state: hₜ₋₁

Cell state: cₜ₋₁

🔹 1. Forget Gate

Decides what to erase from memory.

𝑓
𝑡
=
𝜎
(
𝑊
𝑓
[
ℎ
𝑡
−
1
,
𝑥
𝑡
]
+
𝑏
𝑓
)
f
t
	​

=σ(W
f
	​

[h
t−1
	​

,x
t
	​

]+b
f
	​

)

Output: values in [0,1]

0 → forget completely

1 → keep everything

🔹 2. Input Gate

Decides what new information to store.

𝑖
𝑡
=
𝜎
(
𝑊
𝑖
[
ℎ
𝑡
−
1
,
𝑥
𝑡
]
+
𝑏
𝑖
)
i
t
	​

=σ(W
i
	​

[h
t−1
	​

,x
t
	​

]+b
i
	​

)
𝑐
~
𝑡
=
tanh
⁡
(
𝑊
𝑐
[
ℎ
𝑡
−
1
,
𝑥
𝑡
]
+
𝑏
𝑐
)
c
~
t
	​

=tanh(W
c
	​

[h
t−1
	​

,x
t
	​

]+b
c
	​

)
🔹 3. Cell State Update (Most Important)
𝑐
𝑡
=
𝑓
𝑡
⊙
𝑐
𝑡
−
1
+
𝑖
𝑡
⊙
𝑐
~
𝑡
c
t
	​

=f
t
	​

⊙c
t−1
	​

+i
t
	​

⊙
c
~
t
	​


✅ This linear path allows gradients to flow → no vanishing gradient

🔹 4. Output Gate

Decides what to output.

𝑜
𝑡
=
𝜎
(
𝑊
𝑜
[
ℎ
𝑡
−
1
,
𝑥
𝑡
]
+
𝑏
𝑜
)
o
t
	​

=σ(W
o
	​

[h
t−1
	​

,x
t
	​

]+b
o
	​

)
ℎ
𝑡
=
𝑜
𝑡
⊙
tanh
⁡
(
𝑐
𝑡
)
h
t
	​

=o
t
	​

⊙tanh(c
t
	​

)
4️⃣ Why LSTM Works So Well

Cell state acts like a highway for gradients

Gates prevent unnecessary updates

Can remember dependencies 100s of steps back

That’s the real magic 🧠

5️⃣ LSTM vs RNN vs GRU
Feature	RNN	LSTM	GRU
Long memory	❌	✅	✅
Gates	❌	3 gates	2 gates
Parameters	Low	High	Medium
Training speed	Fast	Slow	Faster

👉 GRU = simpler LSTM (used when data is limited)

6️⃣ Variants You Should Know

Important for interviews + research:

Bi-LSTM → context from past & future

Stacked LSTM → deeper representations

ConvLSTM → video & spatiotemporal data

Attention + LSTM → pre-Transformer era SOTA

7️⃣ Practical Uses (Still Relevant in 2026)

Despite Transformers, LSTMs are used in:

⏱ Time-series forecasting (stocks, sensors)

🧠 Healthcare (ECG, EEG signals)

🔊 Speech processing (low-latency systems)

🏭 Edge devices (less compute than Transformers)

8️⃣ Common Pitfalls (Real Projects)

Needs proper sequence scaling

Slow on very long sequences

Sensitive to batch size & learning rate

Hard to parallelize (vs Transformers)

9️⃣ Interview-Level One-Liner

“LSTM solves vanishing gradients by using a gated cell state that allows selective memory retention over long sequences.”

Memorize this 💡

🔟 When NOT to Use LSTM

❌ Very long documents
❌ NLP tasks with massive data
❌ When parallelization is needed
"""

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts([faqs])

In [ ]:
len(tokenizer.word_index)

252

In [ ]:
tokenizer.word_index

{'\u200b': 1,
 '𝑡': 2,
 't': 3,
 'lstm': 4,
 'to': 5,
 'long': 6,
 '1': 7,
 'cell': 8,
 '→': 9,
 '𝑐': 10,
 'memory': 11,
 'gates': 12,
 'c': 13,
 'gradients': 14,
 'state': 15,
 'ℎ': 16,
 '−': 17,
 'h': 18,
 't−1': 19,
 '❌': 20,
 'term': 21,
 'forget': 22,
 'in': 23,
 'what': 24,
 'output': 25,
 '🔹': 26,
 '𝑓': 27,
 '𝑊': 28,
 '𝑥': 29,
 '𝑏': 30,
 'f': 31,
 'w': 32,
 'x': 33,
 'b': 34,
 '𝑖': 35,
 'i': 36,
 '⊙': 37,
 '𝑜': 38,
 'o': 39,
 'of': 40,
 'vanishing': 41,
 'information': 42,
 'time': 43,
 'this': 44,
 'a': 45,
 'gate': 46,
 'decides': 47,
 '𝜎': 48,
 'σ': 49,
 'tanh': 50,
 '✅': 51,
 'vs': 52,
 'gru': 53,
 'when': 54,
 'data': 55,
 'transformers': 56,
 'why': 57,
 'at': 58,
 'dependencies': 59,
 '👉': 60,
 'that’s': 61,
 'back': 62,
 'by': 63,
 'remember': 64,
 'one': 65,
 'uses': 66,
 'store': 67,
 'the': 68,
 'input': 69,
 'from': 70,
 '0': 71,
 '2': 72,
 '\u2061': 73,
 '3': 74,
 'important': 75,
 'allows': 76,
 'for': 77,
 'real': 78,
 '🧠': 79,
 'rnn': 80,
 'low': 81,
 'slow': 82,

In [ ]:
for sentence in faqs.split('\n'):
  print(sentence)

Why LSTM Exists (Problem First)

Classic RNNs fail at long-term dependencies because of:

Vanishing gradients

Exploding gradients

👉 They forget information that’s far back in time.

LSTM (Long Short-Term Memory) fixes this by controlling what to remember, forget, and output.

2️⃣ Core Idea (One Line)

LSTM uses gates + a memory cell to selectively store long-term information.

Think of it as:

Memory cell = long-term storage

Gates = smart controllers

3️⃣ LSTM Architecture (Inside the Cell)

At time step t, LSTM has:

Input: xₜ

Hidden state: hₜ₋₁

Cell state: cₜ₋₁

🔹 1. Forget Gate

Decides what to erase from memory.

𝑓
𝑡
=
𝜎
(
𝑊
𝑓
[
ℎ
𝑡
−
1
,
𝑥
𝑡
]
+
𝑏
𝑓
)
f
t
	​

=σ(W
f
	​

[h
t−1
	​

,x
t
	​

]+b
f
	​

)

Output: values in [0,1]

0 → forget completely

1 → keep everything

🔹 2. Input Gate

Decides what new information to store.

𝑖
𝑡
=
𝜎
(
𝑊
𝑖
[
ℎ
𝑡
−
1
,
𝑥
𝑡
]
+
𝑏
𝑖
)
i
t
	​

=σ(W
i
	​

[h
t−1
	​

,x
t
	​

]+b
i
	​

)
𝑐
~
𝑡
=
tanh
⁡
(
𝑊
𝑐
[
ℎ
𝑡
−
1
,
𝑥
𝑡
]
+
𝑏
𝑐
)
c
~
t
	​

=tan

In [ ]:
for sentence in faqs.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]
  print(tokenized_sentence)

[57, 4, 87, 88, 89]
[]
[90, 91, 92, 58, 6, 21, 59, 93, 40]
[]
[41, 14]
[]
[94, 14]
[]
[60, 95, 22, 42, 61, 96, 62, 23, 43]
[]
[4, 6, 97, 21, 11, 98, 44, 63, 99, 24, 5, 64, 22, 100, 25]
[]
[101, 102, 103, 65, 104]
[]
[4, 66, 12, 45, 11, 8, 5, 105, 67, 6, 21, 42]
[]
[106, 40, 107, 108]
[]
[11, 8, 6, 21, 109]
[]
[12, 110, 111]
[]
[112, 4, 113, 114, 68, 8]
[]
[58, 43, 115, 3, 4, 116]
[]
[69, 117]
[]
[118, 15, 119]
[]
[8, 15, 120]
[]
[26, 7, 22, 46]
[]
[47, 24, 5, 121, 70, 11]
[]
[27]
[2]
[]
[48]
[]
[28]
[27]
[]
[16]
[2]
[17]
[7]
[]
[29]
[2]
[]
[]
[30]
[27]
[]
[31]
[3]
[1]
[]
[49, 32]
[31]
[1]
[]
[18]
[19]
[1]
[]
[33]
[3]
[1]
[]
[34]
[31]
[1]
[]
[]
[]
[25, 122, 23, 71, 7]
[]
[71, 9, 22, 123]
[]
[7, 9, 124, 125]
[]
[26, 72, 69, 46]
[]
[47, 24, 126, 42, 5, 67]
[]
[35]
[2]
[]
[48]
[]
[28]
[35]
[]
[16]
[2]
[17]
[7]
[]
[29]
[2]
[]
[]
[30]
[35]
[]
[36]
[3]
[1]
[]
[49, 32]
[36]
[1]
[]
[18]
[19]
[1]
[]
[33]
[3]
[1]
[]
[34]
[36]
[1]
[]
[]
[10]
[]
[2]
[]
[50]
[73]
[]
[28]
[10]
[]
[16]
[2]
[17]
[7]
[]

In [ ]:
input_sequences = []
for sentence in faqs.split('\n'):
  tokenized_sentence = tokenizer.texts_to_sequences([sentence])[0]

  for i in range(1,len(tokenized_sentence)):
    input_sequences.append(tokenized_sentence[:i+1])

In [ ]:
input_sequences

[[57, 4],
 [57, 4, 87],
 [57, 4, 87, 88],
 [57, 4, 87, 88, 89],
 [90, 91],
 [90, 91, 92],
 [90, 91, 92, 58],
 [90, 91, 92, 58, 6],
 [90, 91, 92, 58, 6, 21],
 [90, 91, 92, 58, 6, 21, 59],
 [90, 91, 92, 58, 6, 21, 59, 93],
 [90, 91, 92, 58, 6, 21, 59, 93, 40],
 [41, 14],
 [94, 14],
 [60, 95],
 [60, 95, 22],
 [60, 95, 22, 42],
 [60, 95, 22, 42, 61],
 [60, 95, 22, 42, 61, 96],
 [60, 95, 22, 42, 61, 96, 62],
 [60, 95, 22, 42, 61, 96, 62, 23],
 [60, 95, 22, 42, 61, 96, 62, 23, 43],
 [4, 6],
 [4, 6, 97],
 [4, 6, 97, 21],
 [4, 6, 97, 21, 11],
 [4, 6, 97, 21, 11, 98],
 [4, 6, 97, 21, 11, 98, 44],
 [4, 6, 97, 21, 11, 98, 44, 63],
 [4, 6, 97, 21, 11, 98, 44, 63, 99],
 [4, 6, 97, 21, 11, 98, 44, 63, 99, 24],
 [4, 6, 97, 21, 11, 98, 44, 63, 99, 24, 5],
 [4, 6, 97, 21, 11, 98, 44, 63, 99, 24, 5, 64],
 [4, 6, 97, 21, 11, 98, 44, 63, 99, 24, 5, 64, 22],
 [4, 6, 97, 21, 11, 98, 44, 63, 99, 24, 5, 64, 22, 100],
 [4, 6, 97, 21, 11, 98, 44, 63, 99, 24, 5, 64, 22, 100, 25],
 [101, 102],
 [101, 102, 103],
 

In [ ]:
max_len = max([len(x) for x in input_sequences])
print(max_len)

19


In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen = max_len, padding='pre')

In [ ]:
print(padded_input_sequences)

[[  0   0   0 ...   0  57   4]
 [  0   0   0 ...  57   4  87]
 [  0   0   0 ...   4  87  88]
 ...
 [  0   0   0 ...  20  54 251]
 [  0   0   0 ...  54 251  84]
 [  0   0   0 ... 251  84 252]]


In [ ]:
X = padded_input_sequences[:,:-1]
X

array([[  0,   0,   0, ...,   0,   0,  57],
       [  0,   0,   0, ...,   0,  57,   4],
       [  0,   0,   0, ...,  57,   4,  87],
       ...,
       [  0,   0,   0, ...,   0,  20,  54],
       [  0,   0,   0, ...,  20,  54, 251],
       [  0,   0,   0, ...,  54, 251,  84]], dtype=int32)

In [ ]:
y = padded_input_sequences[:,-1]
y

array([  4,  87,  88,  89,  91,  92,  58,   6,  21,  59,  93,  40,  14,
        14,  95,  22,  42,  61,  96,  62,  23,  43,   6,  97,  21,  11,
        98,  44,  63,  99,  24,   5,  64,  22, 100,  25, 102, 103,  65,
       104,  66,  12,  45,  11,   8,   5, 105,  67,   6,  21,  42,  40,
       107, 108,   8,   6,  21, 109, 110, 111,   4, 113, 114,  68,   8,
        43, 115,   3,   4, 116, 117,  15, 119,  15, 120,   7,  22,  46,
        24,   5, 121,  70,  11,  32, 122,  23,  71,   7,   9,  22, 123,
         9, 124, 125,  72,  69,  46,  24, 126,  42,   5,  67,  32,  32,
        74,   8,  15, 127, 128,  75,  44, 130, 131,  76,  14,   5, 132,
         9, 133,  41, 134, 135,  25,  46,  24,   5,  25,  32,  13,  57,
         4, 138, 139, 140,  15, 141, 142,  45, 143,  77,  14, 144, 145,
       146,  64,  59, 148,  40, 149,  62,  68,  78, 150,  79,   4,  52,
        80,  52,  53,  80,   4,  53,  11,  20,  51,  51,  20,  74,  12,
        72,  12,  81, 154, 155, 157, 158,  82, 159,  53, 160,   

In [ ]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y,num_classes=283)

In [ ]:
y.shape

(305, 283)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [ ]:
model = Sequential()
model.add(Embedding(283, 100))
model.add(LSTM(150, return_sequences=True))
model.add(LSTM(150))
model.add(Dense(283, activation='softmax'))

In [ ]:
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_6 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_7 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X,y,epochs=100)

Epoch 1/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 6s 74ms/step - accuracy: 0.0066 - loss: 5.6427
Epoch 2/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 72ms/step - accuracy: 0.0355 - loss: 5.5007
Epoch 3/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 72ms/step - accuracy: 0.0308 - loss: 5.2670
Epoch 4/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 72ms/step - accuracy: 0.0570 - loss: 5.0851
Epoch 5/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 73ms/step - accuracy: 0.0558 - loss: 5.0437
Epoch 6/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 74ms/step - accuracy: 0.0192 - loss: 5.1139
Epoch 7/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 73ms/step - accuracy: 0.0289 - loss: 5.1109
Epoch 8/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 72ms/step - accuracy: 0.0282 - loss: 5.0302
Epoch 9/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 74ms/step - accuracy: 0.0505 - loss: 5.0429
Epoch 10/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 74ms/step - accuracy: 0.0348 - loss: 5.0079
Epoch 11/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 71ms/step - accuracy: 0.0262 - loss: 5.0266
Epoch 12/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 125ms/ste

In [ ]:
import time
import numpy as np
text = "RNNs fail at"

for i in range(10):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=56, padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 353ms/step
RNNs fail at 0
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
RNNs fail at 0 1
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step
RNNs fail at 0 1 long
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step
RNNs fail at 0 1 long term
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
RNNs fail at 0 1 long term dependencies
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
RNNs fail at 0 1 long term dependencies because
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
RNNs fail at 0 1 long term dependencies because of
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step
RNNs fail at 0 1 long term dependencies because of because
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
RNNs fail at 0 1 long term dependencies because of because of
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
RNNs fail at 0 1 long term dependencies because of because of by
